[versions]

# plugins
kotlin = "2.2.0"
gradleIntelliJPlugin = "2.7.0"

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
